import type { PropertyMetadata, PropertyType } from './types';

// Registry of all property types with their metadata
export const PROPERTY_REGISTRY: Record<PropertyType, PropertyMetadata> = {
  text: {
    type: 'text',
    icon: 'T',
    label: 'Text',
    description: 'Single line of text',
    defaultWidth: 200,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: false,
  },
  number: {
    type: 'number',
    icon: '#',
    label: 'Number',
    description: 'Numeric value with formatting',
    defaultWidth: 120,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: false,
  },
  select: {
    type: 'select',
    icon: '▼',
    label: 'Select',
    description: 'Single option from a list',
    defaultWidth: 150,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: true,
  },
  multiSelect: {
    type: 'multiSelect',
    icon: '▼',
    label: 'Multi-select',
    description: 'Multiple options from a list',
    defaultWidth: 200,
    supportsFiltering: true,
    supportsSorting: false,
    supportsGrouping: true,
  },
  date: {
    type: 'date',
    icon: '📆',
    label: 'Date',
    description: 'Date with optional time',
    defaultWidth: 150,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: true,
  },
  person: {
    type: 'person',
    icon: '@',
    label: 'Person',
    description: 'User assignment',
    defaultWidth: 150,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: true,
  },
  url: {
    type: 'url',
    icon: '🔗',
    label: 'URL',
    description: 'Web link',
    defaultWidth: 200,
    supportsFiltering: true,
    supportsSorting: false,
    supportsGrouping: false,
  },
  email: {
    type: 'email',
    icon: '@',
    label: 'Email',
    description: 'Email address',
    defaultWidth: 200,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: false,
  },
  phone: {
    type: 'phone',
    icon: '☎',
    label: 'Phone',
    description: 'Phone number',
    defaultWidth: 150,
    supportsFiltering: true,
    supportsSorting: false,
    supportsGrouping: false,
  },
  checkbox: {
    type: 'checkbox',
    icon: '☑',
    label: 'Checkbox',
    description: 'Boolean toggle',
    defaultWidth: 80,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: true,
  },
  rating: {
    type: 'rating',
    icon: '★',
    label: 'Rating',
    description: 'Star rating',
    defaultWidth: 120,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: false,
  },
  progress: {
    type: 'progress',
    icon: '▬',
    label: 'Progress',
    description: 'Progress bar',
    defaultWidth: 150,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: false,
  },
  status: {
    type: 'status',
    icon: '◉',
    label: 'Status',
    description: 'Status with color',
    defaultWidth: 150,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: true,
  },
  tags: {
    type: 'tags',
    icon: '▼',
    label: 'Tags',
    description: 'Multiple tags',
    defaultWidth: 200,
    supportsFiltering: true,
    supportsSorting: false,
    supportsGrouping: true,
  },
  relation: {
    type: 'relation',
    icon: '↔',
    label: 'Relation',
    description: 'Link to another record',
    defaultWidth: 180,
    supportsFiltering: true,
    supportsSorting: false,
    supportsGrouping: true,
  },
  rollup: {
    type: 'rollup',
    icon: 'Σ',
    label: 'Rollup',
    description: 'Aggregate from relations',
    defaultWidth: 120,
    supportsFiltering: true,
    supportsSorting: true,
    supportsGrouping: false,
  },
  formula: {
    type: 'formula',
    icon: 'ƒ',
    label: 'Formula',
    description: 'Calculated field',
    defaultWidth: 150,
    supportsFiltering: false,
    supportsSorting: true,
    supportsGrouping: false,
  },
};

export function getPropertyMetadata(type: PropertyType): PropertyMetadata {
  return PROPERTY_REGISTRY[type];
}

export function getAllPropertyTypes(): PropertyType[] {
  return Object.keys(PROPERTY_REGISTRY) as PropertyType[];
}
